/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/cuppingHand.glb --types -M --output src/3DModels/CuppingHand.tsx 
*/

import * as THREE from 'three'
import React, { MutableRefObject, useEffect, useState } from 'react'
import { Clone, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { motion } from 'framer-motion-3d'
import router from 'next/router'
import { useAnimation } from 'framer-motion'

type GLTFResult = GLTF & {
  nodes: {
    Shape_IndexedFaceSet001: THREE.Mesh
  }
  materials: {
    Arms__Standard_: THREE.MeshStandardMaterial
  }
  animations: any[]
}

type HeadHandsProps = {
  scroll: MutableRefObject<number>;
} & JSX.IntrinsicElements['group'];


export function CuppingHand({ scroll, ...groupProps }: HeadHandsProps) {
  const { nodes, materials } = useGLTF('/cuppingHand.glb') as GLTFResult
  const [disposed, setDisposed] = useState(true);
  const [isInPage, setIsInPage] = useState(false);
  const materialControls = useAnimation()

  useEffect(() => {
    if (router.pathname === "/business/innotrinsic") {
      if (scroll.current > 0.015) {
        materialControls.start({ opacity: 0 }).then(() => setIsInPage(true));
      } else {
        setIsInPage(true);
        materialControls.start({ opacity: 1 });
      }
    } else {
      materialControls.start({ opacity: 0 }).then(() => setIsInPage(false))
    }
  }, [router.pathname, scroll.current]);


  useEffect(() => {
    if (!isInPage) {
      setTimeout(() => setDisposed(true), 0);
    } else {
      setDisposed(false);
    }
  }, [isInPage]);


  return (
    <group visible={!disposed} {...groupProps} dispose={null}>
      <mesh
        geometry={nodes.Shape_IndexedFaceSet001.geometry}
        position={[-0.222, -0.02, 0.054]}
        rotation={[0.07, -0.381, 2.429]} >
        <motion.meshStandardMaterial
          initial="initial"
          animate={materialControls}
          {...materials.Arms__Standard_}
          transparent
          needsUpdate
        /></mesh>
      <Clone
        scale={[-1, 1, 1]}
        rotation={[0.07, 0.381, -2.129]}
        position={[0.55, 0, 0]}
        object={nodes.Shape_IndexedFaceSet001}
      >
        <motion.meshStandardMaterial
          initial="initial"
          animate={materialControls}
          {...materials.Arms__Standard_}
          transparent
          needsUpdate
        />
      </Clone>
    </group >
  )
}

useGLTF.preload('/cuppingHand.glb')
