/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/mountain2.glb --types --output src/3DModels/Mountain2.tsx 
*/

import * as THREE from 'three'
import React, { MutableRefObject, useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { loc } from '@/ts/atoms'
import { useFrame } from '@react-three/fiber'
import { useAnimation } from 'framer-motion'
import { useAtom } from 'jotai'
import { useSearchParams } from 'next/navigation'
import { useRouter } from 'next/router'
import { lerp } from 'three/src/math/MathUtils.js'

type ActionName =
  | 'Landscape.004_cell.001Action'
  | 'Landscape.004_cell.012Action'
  | 'Landscape.004_cell.016Action'
  | 'Landscape.004_cell.019Action'
  | 'Landscape.004_cell.020Action'
  | 'Landscape.004_cell.021Action'
  | 'Landscape.004_cell.022Action'
  | 'Landscape.004_cell.023Action'
  | 'Landscape.004_cell.031Action'
  | 'Landscape.004_cell.032Action'
  | 'mountain_topAction'
  | 'Landscape.004_cell.035Action'
  | 'Landscape.004_cell.036Action'
  | 'Landscape.004_cell.037Action'
  | 'Landscape.004_cell.040Action'
  | 'Landscape.004_cell.044Action'
  | 'Landscape.004_cell.046Action'
  | 'Landscape.004_cell.050Action'
  | 'Landscape.004_cell.051Action'
  | 'Landscape.004_cell.052Action'
  | 'Landscape.004_cell.053Action'
  | 'Landscape.004_cell.054Action'
  | 'Landscape.004_cell.055Action'
  | 'Landscape.004_cell.056Action'
  | 'Landscape.004_cell.057Action'
  | 'Landscape.004_cell.058Action'
  | 'Landscape.004_cell.060Action'
  | 'Landscape.004_cell.061Action'
  | 'Landscape.004_cell.063Action'
  | 'Landscape.004_cell.064Action'
  | 'Landscape.004_cell.067Action'
  | 'Landscape.004_cell.068Action'
  | 'Landscape.004_cell.070Action'
  | 'Landscape.004_cell.071Action'
  | 'Landscape.004_cell.074Action'
  | 'Landscape.004_cell.079Action'
  | 'Landscape.004_cell.081Action'
  | 'Landscape.004_cell.085Action'
  | 'Landscape.004_cell.086Action'
  | 'Landscape.004_cell.092Action'
  | 'Landscape.004_cell.096Action'
  | 'Landscape.004_cell.098Action'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Landscape004_cell001: THREE.Mesh
    Landscape004_cell012: THREE.Mesh
    Landscape004_cell016: THREE.Mesh
    Landscape004_cell019: THREE.Mesh
    Landscape004_cell020: THREE.Mesh
    Landscape004_cell021: THREE.Mesh
    Landscape004_cell022: THREE.Mesh
    Landscape004_cell023: THREE.Mesh
    Landscape004_cell031: THREE.Mesh
    Landscape004_cell032: THREE.Mesh
    mountain_top: THREE.Mesh
    Landscape004_cell035: THREE.Mesh
    Landscape004_cell036: THREE.Mesh
    Landscape004_cell037: THREE.Mesh
    Landscape004_cell040: THREE.Mesh
    Landscape004_cell044: THREE.Mesh
    Landscape004_cell046: THREE.Mesh
    Landscape004_cell050: THREE.Mesh
    Landscape004_cell051: THREE.Mesh
    Landscape004_cell052: THREE.Mesh
    Landscape004_cell053: THREE.Mesh
    Landscape004_cell054: THREE.Mesh
    Landscape004_cell055: THREE.Mesh
    Landscape004_cell056: THREE.Mesh
    Landscape004_cell057: THREE.Mesh
    Landscape004_cell058: THREE.Mesh
    Landscape004_cell060: THREE.Mesh
    Landscape004_cell061: THREE.Mesh
    Landscape004_cell063: THREE.Mesh
    Landscape004_cell064: THREE.Mesh
    Landscape004_cell067: THREE.Mesh
    Landscape004_cell068: THREE.Mesh
    Landscape004_cell070: THREE.Mesh
    Landscape004_cell071: THREE.Mesh
    Landscape004_cell074: THREE.Mesh
    Landscape004_cell079: THREE.Mesh
    Landscape004_cell081: THREE.Mesh
    Landscape004_cell085: THREE.Mesh
    Landscape004_cell086: THREE.Mesh
    Landscape004_cell092: THREE.Mesh
    Landscape004_cell096: THREE.Mesh
    Landscape004_cell098: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type MountainType = {
  props?: JSX.IntrinsicElements['group'];
  scroll: MutableRefObject<number>;
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Mountain2(props: MountainType) {
  // router
  const router = useRouter()
  // search params
  const searchParams = useSearchParams();
  //atoms
  const [location, useLocation] = useAtom(loc)
  // mount states
  const [isInPage, setIsInPage] = useState(false);
  const [disposed, setDisposed] = useState(false);
  //refs
  const group = useRef<any>()
  //scene
  const { nodes, materials, animations }: any = useGLTF('/mountain2.glb') as GLTFResult;
  //animations
  const { actions }: any = useAnimations(animations, group)
  // controls
  const controls = useAnimation();


  //uef
  useEffect(() => {
    if (
      location === "landingBusiness" && router.pathname === "/business" && searchParams.get("test") === null || false) {
      setDisposed(false), setIsInPage(true);
    } else {
      controls.start("exit").then(() => {
        setTimeout(() => {
          setDisposed(true),
            setIsInPage(false);
        }, 500)
      })
    }
  }, [router.pathname, searchParams, location])

  useEffect(() => {
    isInPage && controls.start("enter")
  }, [isInPage]);

  useEffect(() => {
    Object.values(actions).map((animation: any) => {
      animation.reset().fadeIn(0.5).play().paused = true
    })

  }, [])

  //render loop
  useFrame((state) => {
    group.current.position.z = lerp(group.current.position.z, props.scroll.current * 50, 0.02)
    group.current.rotation.y = lerp(group.current.rotation.y, -1.5 - props.scroll.current * 5, 0.02)
    Object.values(actions).map((animation: any) => {
      animation.time = lerp(animation.time, animation.getClip().duration * props.scroll.current * 5, 0.02)
    });
  });
  return (
    <group scale={10} position={[0, -2, 0]} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Landscape004_cell001" geometry={nodes.Landscape004_cell001.geometry} material={materials['Material.001']} position={[-0.3, 0.03, -0.123]} />
        <mesh name="Landscape004_cell012" geometry={nodes.Landscape004_cell012.geometry} material={materials['Material.001']} position={[-0.198, 0.029, -0.178]} />
        <mesh name="Landscape004_cell016" geometry={nodes.Landscape004_cell016.geometry} material={materials['Material.001']} position={[0.009, 0.054, 0.292]} />
        <mesh name="Landscape004_cell019" geometry={nodes.Landscape004_cell019.geometry} material={materials['Material.001']} position={[0.231, 0.093, -0.138]} />
        <mesh name="Landscape004_cell020" geometry={nodes.Landscape004_cell020.geometry} material={materials['Material.001']} position={[-0.093, 0.044, 0.314]} />
        <mesh name="Landscape004_cell021" geometry={nodes.Landscape004_cell021.geometry} material={materials['Material.001']} position={[0.228, 0.041, -0.253]} />
        <mesh name="Landscape004_cell022" geometry={nodes.Landscape004_cell022.geometry} material={materials['Material.001']} position={[0.21, 0.096, 0.201]} />
        <mesh name="Landscape004_cell023" geometry={nodes.Landscape004_cell023.geometry} material={materials['Material.001']} position={[-0.143, 0.053, -0.174]} />
        <mesh name="Landscape004_cell031" geometry={nodes.Landscape004_cell031.geometry} material={materials['Material.001']} position={[-0.118, 0.036, -0.224]} />
        <mesh name="Landscape004_cell032" geometry={nodes.Landscape004_cell032.geometry} material={materials['Material.001']} position={[0.35, 0.04, 0.085]} />
        <mesh name="mountain_top" geometry={nodes.mountain_top.geometry} material={materials['Material.001']} position={[0.202, 0.203, 0.047]} />
        <mesh name="Landscape004_cell035" geometry={nodes.Landscape004_cell035.geometry} material={materials['Material.001']} position={[-0.347, 0.029, 0.214]} />
        <mesh name="Landscape004_cell036" geometry={nodes.Landscape004_cell036.geometry} material={materials['Material.001']} position={[-0.269, 0.034, -0.139]} />
        <mesh name="Landscape004_cell037" geometry={nodes.Landscape004_cell037.geometry} material={materials['Material.001']} position={[0.138, 0.056, 0.305]} />
        <mesh name="Landscape004_cell040" geometry={nodes.Landscape004_cell040.geometry} material={materials['Material.001']} position={[-0.369, 0.04, -0.009]} />
        <mesh name="Landscape004_cell044" geometry={nodes.Landscape004_cell044.geometry} material={materials['Material.001']} position={[-0.154, 0.085, 0.23]} />
        <mesh name="Landscape004_cell046" geometry={nodes.Landscape004_cell046.geometry} material={materials['Material.001']} position={[0.292, 0.08, 0.155]} />
        <mesh name="Landscape004_cell050" geometry={nodes.Landscape004_cell050.geometry} material={materials['Material.001']} position={[-0.322, 0.024, -0.117]} />
        <mesh name="Landscape004_cell051" geometry={nodes.Landscape004_cell051.geometry} material={materials['Material.001']} position={[0.083, 0.064, -0.245]} />
        <mesh name="Landscape004_cell052" geometry={nodes.Landscape004_cell052.geometry} material={materials['Material.001']} position={[-0.321, 0.042, -0.081]} />
        <mesh name="Landscape004_cell053" geometry={nodes.Landscape004_cell053.geometry} material={materials['Material.001']} position={[-0.29, 0.05, 0.223]} />
        <mesh name="Landscape004_cell054" geometry={nodes.Landscape004_cell054.geometry} material={materials['Material.001']} position={[0.145, 0.053, -0.246]} />
        <mesh name="Landscape004_cell055" geometry={nodes.Landscape004_cell055.geometry} material={materials['Material.001']} position={[-0.22, 0.044, 0.289]} />
        <mesh name="Landscape004_cell056" geometry={nodes.Landscape004_cell056.geometry} material={materials['Material.001']} position={[0.171, 0.022, -0.293]} />
        <mesh name="Landscape004_cell057" geometry={nodes.Landscape004_cell057.geometry} material={materials['Material.001']} position={[-0.37, 0.038, -0.047]} />
        <mesh name="Landscape004_cell058" geometry={nodes.Landscape004_cell058.geometry} material={materials['Material.001']} position={[0.312, 0.035, -0.134]} />
        <mesh name="Landscape004_cell060" geometry={nodes.Landscape004_cell060.geometry} material={materials['Material.001']} position={[-0.232, 0.076, 0.207]} />
        <mesh name="Landscape004_cell061" geometry={nodes.Landscape004_cell061.geometry} material={materials['Material.001']} position={[0.002, 0.027, 0.328]} />
        <mesh name="Landscape004_cell063" geometry={nodes.Landscape004_cell063.geometry} material={materials['Material.001']} position={[-0.3, 0.025, 0.256]} />
        <mesh name="Landscape004_cell064" geometry={nodes.Landscape004_cell064.geometry} material={materials['Material.001']} position={[0.039, 0.083, 0.234]} />
        <mesh name="Landscape004_cell067" geometry={nodes.Landscape004_cell067.geometry} material={materials['Material.001']} position={[-0.188, 0.091, 0.253]} />
        <mesh name="Landscape004_cell068" geometry={nodes.Landscape004_cell068.geometry} material={materials['Material.001']} position={[-0.037, 0.081, 0.256]} />
        <mesh name="Landscape004_cell070" geometry={nodes.Landscape004_cell070.geometry} material={materials['Material.001']} position={[-0.362, 0.058, 0.066]} />
        <mesh name="Landscape004_cell071" geometry={nodes.Landscape004_cell071.geometry} material={materials['Material.001']} position={[-0.059, 0.074, -0.175]} />
        <mesh name="Landscape004_cell074" geometry={nodes.Landscape004_cell074.geometry} material={materials['Material.001']} position={[0.242, 0.047, 0.278]} />
        <mesh name="Landscape004_cell079" geometry={nodes.Landscape004_cell079.geometry} material={materials['Material.001']} position={[0.059, 0.038, 0.318]} />
        <mesh name="Landscape004_cell081" geometry={nodes.Landscape004_cell081.geometry} material={materials['Material.001']} position={[-0.335, 0.08, 0.157]} />
        <mesh name="Landscape004_cell085" geometry={nodes.Landscape004_cell085.geometry} material={materials['Material.001']} position={[0.285, 0.097, 0.001]} />
        <mesh name="Landscape004_cell086" geometry={nodes.Landscape004_cell086.geometry} material={materials['Material.001']} position={[-0.039, 0.044, -0.247]} />
        <mesh name="Landscape004_cell092" geometry={nodes.Landscape004_cell092.geometry} material={materials['Material.001']} position={[-0.256, 0.021, -0.169]} />
        <mesh name="Landscape004_cell096" geometry={nodes.Landscape004_cell096.geometry} material={materials['Material.001']} position={[0.037, 0.044, -0.267]} />
        <mesh name="Landscape004_cell098" geometry={nodes.Landscape004_cell098.geometry} material={materials['Material.001']} position={[0.319, 0.033, 0.207]} />
      </group>
    </group>
  )
}

useGLTF.preload('/mountain2.glb')
