/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/newHead.glb --types --output src/NewHead.tsx 
*/

import React, {
  MutableRefObject,
  Suspense,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import {
  Float,
  MeshTransmissionMaterial,
  useAspect,
  useGLTF,
} from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { motion as motion3d } from "framer-motion-3d";
import { useFrame, useThree } from "@react-three/fiber";
import { useAtom } from "jotai";
import { useRouter } from "next/router";
import { useAnimation } from "framer-motion";
import { useSearchParams } from "next/navigation";
import { SkinnedMesh } from "three/src/objects/SkinnedMesh.js";
import { Bone } from "three/src/objects/Bone.js";
import { Model } from "./GhostHand";
import { Mesh } from "three/src/objects/Mesh.js";
import { size as s, transition } from "../ts/utils";
import { extend } from "@react-three/fiber";
import {
  productViewer,
  globalTarget,
  orbitTarget,
  loc,
  imageViewer,
} from "@/ts/atoms";
import IdeaCloud from "@/ts/landingGL/IdeaCloud";
import { ShaderHand } from "./texHand";
import { TexturedHand } from "./texHand2";
import WordCloud from "@/ts/brainBasicsGL/WordCloud";
import Camouflage, {
  CamouflageShaderMaterial,
} from "@/ts/brainBasicsGL/Camouflage";
import { AdditiveBlending, Group, MathUtils, Vector2, Vector3 } from "three";
import * as BufferGeometryUtils from "@/ts/threeExport/BufferGeometryUtils";

import { lerp } from "three/src/math/MathUtils.js";
import { LRBrain } from "./LRBrain";
import { CuppingHand } from "./CuppingHand";

const GoldShader = (
  <shaderMaterial
    uniforms={{
      uTime: { value: 0.0 },
      uResolution: { value: new Vector2() },
      uCameraPosition: { value: new Vector3() },
    }}
    vertexShader={`
    varying vec3 vNormal;
    varying vec3 vPosition;
    void main() {
      vNormal = normalize(normalMatrix * normal);
      vPosition = (modelViewMatrix * vec4(position, 1.0)).xyz;
      gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
    }
  `}
    fragmentShader={`
    uniform vec3 uCameraPosition;
    varying vec3 vNormal;
    varying vec3 vPosition;
    
    void main() {
      vec3 viewDir = normalize(uCameraPosition - vPosition);
      vec3 reflectDir = reflect(viewDir, normalize(vNormal));
      
      vec3 baseColor = vec3(1.0, 0.64, 0.0);
      vec3 ambient = 0.2 * baseColor;
      vec3 diffuse = 0.8 * baseColor * max(dot(normalize(vNormal), normalize(viewDir)), 0.0);
      vec3 specular = vec3(1.0) * pow(max(dot(viewDir, reflectDir), 0.0), 32.0);

      gl_FragColor = vec4(ambient + diffuse + specular, 1.0);
    }
  `}
  />
);

extend({ GoldShader });

export default GoldShader;

type GLTFResult = GLTF & {
  nodes: {
    stem: Mesh;
  };
  materials: {};
  animations: any[];
};

type HeadHandsProps = {
  scroll: MutableRefObject<number>;
  props?: JSX.IntrinsicElements["group"];
};

const brainVariants = {
  initial: { scale: 0, rotateX: 0, rotateY: 0, x: 0, y: 1.65, z: 0 },
  focus: { scale: 0.1, rotateX: 0, rotateY: 0, x: 0, y: 1.65, z: 0 },
  innotrinsic: { scale: 1, rotateY: 1.54, rotateX: 1, x: 0.15, y: 1.925, z: 0.1, transition: transition({ delay: 0 }) },
  enter: { scale: 1, rotateX: 0, rotateY: 0, x: 0, y: 1.65, z: 0, transition: transition({ delay: 0.5 }) },
  exit: { scale: 0, rotateX: 0, rotateY: 0, x: 0, y: 1.65, z: 0 },
};

const material2Variants = {
  initial: {
    opacity: 0,
    reflectivity: 0.7,
    roughness: 0.125,
    color: "#f0c25e",
    metalness: 1,
    sheenRoughness: 0.2,
    iridescence: 0.5,
    iridescenceIOR: 0.85,
    clearcoat: 1,
    clearcoatRoughness: 0,
  },
  hidden: {
    opacity: 0,
    reflectivity: 0.7,
    color: "#f0c25e",
    metalness: 1,
  },
  hide: {
    opacity: 0.1,
    reflectivity: 0.7,
    color: "#f0c25e",
    metalness: 1,
  },
  brainbackgrounds: {
    opacity: 0.5,
    color: "#5485d4",
    reflectivity: 0.7,
    metalness: 1,
    sheenRoughness: 0.2,
    iridescence: 0.0,
    iridescenceIOR: 0.2,
    clearcoat: 1,
    clearcoatRoughness: 0.2,
  },
  innotrinsic: {
    opacity: 1,
    color: "#1b4a74",
    reflectivity: 0,
    metalness: 0,
    sheenRoughness: 0.2,
    iridescence: 0,
    iridescenceIOR: 0,
    clearcoat: 1,
    clearcoatRoughness: 0.2,
  },
  enter: {
    color: "#f0c25e",
    opacity: 1,
    reflectivity: 0.7,
    metalness: 1,
    roughness: 0.125,
    sheenRoughness: 0.2,
    iridescence: 0.5,
    iridescenceIOR: 0.85,

    transition: {
      type: "spring",
      damping: 10,
      stiffness: 50,
      restDelta: 0.1,
      delay: 0.5,
    },
  },
  exit: {
    opacity: 0,
    color: "#f0c25e",
    reflectivity: 0.7,
    metalness: 1,
    transition: {
      type: "spring",
      damping: 10,
      stiffness: 50,
      restDelta: 0.1,
      delay: 0.25,
    },
  },
};

const words = [
  "Think",
  "Act",
  "Move",
  "Motivation",
  "Satisfaction",
  "Flexible",
  "Exzellenz",
  "Kreativität",
  "Entscheiden",
  "Problemlösung",
  "Adaptability",
  "Fokus",
  "Resilienz",
  "Kollaboration",
  "Courage",
  "Engagement",
  "Effizienz",
  "Productivity",
];
const colors = [
  "#92a9c5",
  "#f4f9ff",
  "#ffffff",
  "#c6dfe8",
  "#f4e4ad",
  "#f0f7ff",
  "#e7f1ff",
  "#eeeac9",
  "#ecf8ff",
  "#f8f1cd",
  "#b1cef0",
  "#e8ce86",
  "#dde5f0",
  "#fffdec",
  "#bed0ef",
  "#cfdff0",
];

export function NewHead4(props: HeadHandsProps) {
  const { nodes, materials } = useGLTF("/highrez_brain.glb") as GLTFResult;
  const [pvAtom, setPVAtom] = useAtom(productViewer);
  const [ivAtom, setIVAtom] = useAtom(imageViewer);
  const [gTarget, setGTarget] = useAtom(globalTarget);
  const [target, setTarget] = useAtom(orbitTarget);
  const [app, setApp] = useAtom(loc);
  const [pos, setPos] = useState<any>([]);
  const [pos2, setPos2] = useState<any>([]);
  const [scl, setScale] = useState<any>([]);
  const { viewport, size } = useThree();
  const [w, h] = useAspect(size.width, size.height);
  const router = useRouter();

  //refs
  const group = useRef<Group>(null);
  const [location, setLocation] = useAtom(loc);

  //searchParams
  const searchParams = useSearchParams();

  // animation controls

  const brain_material_controls = useAnimation();

  // states

  const [isInPage, setIsInPage] = useState(false);
  const [disposed, setDisposed] = useState(false);

  useEffect(() => {
    const scale: any = [
      (pvAtom?.width / window.innerWidth) * viewport?.width,
      (pvAtom?.height / window.innerHeight) * viewport?.height,
      1,
    ];
    const position: any = [
      ((pvAtom?.width / window.innerWidth) * viewport.width) / 2 -
      viewport.width / 2 +
      (pvAtom?.left / window.innerWidth) * viewport.width,
      (router.pathname === "/business/brainbackgrounds"
        ? -s(15, viewport.width / 1.35, 19)
        : -s(11, viewport.width / 1.35, 14)) -
      ((pvAtom?.height / window.innerHeight) * viewport.height) / 2 +
      viewport.height / 2 -
      (pvAtom?.top / window.innerHeight) * viewport.height,
      0,
    ];
    setPos(position);
    setScale(scale);
  }, [pvAtom]);

  const bmRef = useRef<any>(!null);
  const glassRef = useRef<any>(!null);

  const brain_material = (
    <motion3d.meshPhysicalMaterial
      ref={bmRef}
      initial="initial"
      color={"#f0c25e"}
      transmission={0.5}
      ior={1.32}
      thickness={0.5}
      animate={brain_material_controls}
      exit="exit"
      variants={material2Variants}
      roughness={0.2}
      reflectivity={0}
      toneMapped
      transparent
      sheen={0.2}
      sheenColor={"#fff87b"}

    />
  );

  const brain_mesh_controls = useAnimation();

  // enter animations

  useEffect(() => {
    if (router.pathname === "/") {
      setIsInPage(true);
      if (props.scroll.current > 0.015) {
        brain_material_controls.start("hidden").then(() => {
          setIsInPage(false);
        });
      } else {
        setIsInPage(true);
        brain_mesh_controls.start("enter");
        brain_material_controls.start("enter");
      }
    } else if (router.pathname === "/einsatzgebiete") {
      if (searchParams.get("view") && !searchParams.get("focusGroup")) {
        brain_material_controls.start("hide");
      } else if (searchParams.get("view") && searchParams.get("focusGroup")) {
        brain_material_controls.start("hidden").then(() => {
          setIsInPage(false);
        });
      } else {
        setIsInPage(true);
        brain_mesh_controls.start("enter");
        brain_material_controls.start("enter");
      }
    } else if (router.pathname === "/business/brainbackgrounds") {
      if (props.scroll.current > 0.015) {
        brain_material_controls.start("hidden").then(() => {
          setIsInPage(false);
        });
      } else {
        setIsInPage(true);
        brain_mesh_controls.start("enter");
        brain_material_controls.start("brainbackgrounds");
      }
    } else if (router.pathname === "/business/innotrinsic") {
      if (props.scroll.current > 0.015) {
        brain_material_controls.start("hidden").then(() => {
          setIsInPage(false);
        });
      } else {
        setIsInPage(true);
        brain_mesh_controls.start("innotrinsic");
        brain_material_controls.start("innotrinsic");
      }
    } else {
      brain_material_controls.start("hidden").then(() => {
        setIsInPage(false);
      });
    }
  }, [router.pathname, props.scroll.current, searchParams]);

  useEffect(() => {
    if (!isInPage) {
      setTimeout(() => setDisposed(true), 0);
    } else {
      setDisposed(false);
    }
  }, [isInPage]);

  const light = useRef(null)

  return (
    <group
      {...props}
      ref={group}
      position={pos}
      dispose={null}
      scale={
        router.pathname === "/business/brainbackgrounds"
          ? s(11, scl[0] * s(0.5, viewport.width / 20, 1.5), 14)
          : s(7, scl[0] * s(0.5, viewport.width / 30, 0.8), 10)
      }
      rotation={[0, -Math.PI / 1.15, 0]}
    >
      <CuppingHand
        scroll={props.scroll}
        rotation={[2, 0.274, -2.84]}
        position={[0.175, 0.9, 0]}
        scale={1}
      />

      <group rotation={[0, -0.3, 0]} scale={1}>
        <LRBrain scroll={props.scroll} props={{ position: ([1, 0, 0]) }} />
        <ShaderHand scroll={props.scroll} />
        <TexturedHand />
      </group>
      <Float
        floatIntensity={router.pathname !== "business/innotrinsic" ? 0 : 0.1}
        rotationIntensity={router.pathname !== "business/innotrinsic" ? 0 : 0.1}
      >

        <motion3d.group
          visible={!disposed}
          rotation={[0, -Math.PI / 0.85, 0]}
          position={[0.075, -0.6, 0.1]}
        >
          <WordCloud
            scroll={props.scroll}
            active={router.pathname === "/business/brainbackgrounds"}
            words={words}
            colors={colors}
          />
          <motion3d.group>
            <pointLight
              intensity={15}
              color={"#ffde5b"}
              position={[0.2, 1.5, 0]}
            />
            <motion3d.mesh
              scale={1}
              variants={brainVariants}
              initial="initial"
              animate={brain_mesh_controls}

              geometry={nodes.stem.geometry}
              position={[0, 1.7, -0.05]}
            >
              {brain_material}
            </motion3d.mesh>
          </motion3d.group>
          <Suspense fallback={null}>
            <group position={[0.115, 1.9, 0]} scale={0.25}>
              <IdeaCloud scroll={props.scroll} centerPoint={[0, 0, 0]} />
            </group>
          </Suspense>
        </motion3d.group>
      </Float>
    </group>
  );
}

// useGLTF.preload('/newHead4.glb')
