/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/mountain.glb --types --output src/Mountain.tsx 
*/

import * as THREE from 'three'
import React, { MutableRefObject, useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame, useThree } from '@react-three/fiber'
import { lerp } from './ts/threeExport/math/MathUtils'
import { motion as motion3d } from "framer-motion-3d"
import { size } from './ts/utils'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Circle: THREE.Mesh
    Circle002_1: THREE.Mesh
    Circle002_2: THREE.Mesh
    Cylinder003: THREE.Mesh
    Circle001_cell: THREE.Mesh
    Circle001_cell001: THREE.Mesh
    Circle001_cell001_1: THREE.Mesh
    Circle001_cell002_1: THREE.Mesh
    Circle001_cell002_2: THREE.Mesh
    Circle001_cell003: THREE.Mesh
    Circle001_cell003_1: THREE.Mesh
    Circle001_cell004_1: THREE.Mesh
    Circle001_cell004_2: THREE.Mesh
    Circle001_cell005_1: THREE.Mesh
    Circle001_cell005_2: THREE.Mesh
    Circle001_cell006_1: THREE.Mesh
    Circle001_cell006_2: THREE.Mesh
    Circle001_cell007_1: THREE.Mesh
    Circle001_cell007_2: THREE.Mesh
    Circle001_cell008: THREE.Mesh
    Circle001_cell008_1: THREE.Mesh
    Circle001_cell009_1: THREE.Mesh
    Circle001_cell009_2: THREE.Mesh
    Circle001_cell010_1: THREE.Mesh
    Circle001_cell010_2: THREE.Mesh
    Circle001_cell011_1: THREE.Mesh
    Circle001_cell011_2: THREE.Mesh
    Circle001_cell012: THREE.Mesh
    Circle001_cell012_1: THREE.Mesh
    Circle001_cell013_1: THREE.Mesh
    Circle001_cell013_2: THREE.Mesh
    Circle001_cell014_1: THREE.Mesh
    Circle001_cell014_2: THREE.Mesh
    Circle001_cell015_1: THREE.Mesh
    Circle001_cell015_2: THREE.Mesh
    Circle001_cell016_1: THREE.Mesh
    Circle001_cell016_2: THREE.Mesh
    Circle001_cell017_1: THREE.Mesh
    Circle001_cell017_2: THREE.Mesh
    Circle001_cell018: THREE.Mesh
    Circle001_cell018_1: THREE.Mesh
    Circle001_cell019_1: THREE.Mesh
    Circle001_cell019_2: THREE.Mesh
    Circle001_cell020: THREE.Mesh
    Circle001_cell020_1: THREE.Mesh
    Circle001_cell021_1: THREE.Mesh
    Circle001_cell021_2: THREE.Mesh
  }
  materials: {
    rock: THREE.MeshStandardMaterial
    snow: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ActionName = 'CubeAction' | 'Circle' | 'Circle.002Action' | 'Empty' | 'CylinderAction.003' | 'Circle.001_cell' | 'Circle.001_cell.002' | 'Circle.001_cell.004' | 'Circle.001_cell.005' | 'Circle.001_cell.006' | 'Circle.001_cell.007' | 'Circle.001_cell.009' | 'Circle.001_cell.010' | 'Circle.001_cell.011' | 'Circle.001_cell.013' | 'Circle.001_cell.014' | 'Circle.001_cell.015' | 'Circle.001_cell.016' | 'Circle.001_cell.017' | 'Circle.001_cell.019' | 'Circle.001_cell.021' | 'Circle.001_cell.022' | 'Circle.001_cell.023' | 'Circle.001_cell.025' | 'Circle.001_cell.026' | 'Circle.001_cell.027' | 'Circle.001_cell.028'
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}


type MountainType = {
  props?: JSX.IntrinsicElements['group'];
  scroll: MutableRefObject<number>;
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Mountain(props: MountainType) {
  //refs
  const group: any = useRef<THREE.Group>()
  //scene
  const { nodes, materials, animations }: any = useGLTF('/mountain.glb') as GLTFResult
  //animations
  const { actions }: any = useAnimations(animations, group)
  // materials
  const rope = (
    <motion3d.meshStandardMaterial
      color="#EDDFAB"
      transparent
      toneMapped
    />
  );

  const brain = (
    <motion3d.meshStandardMaterial
      color="#B0E431"
      transparent
      opacity={1}
      toneMapped
    />
  );

  //uef
  useEffect(() => {
    Object.values(actions).map((animation: any) => {
      animation.reset().fadeIn(0.5).play().paused = true
    })

  }, [])

  //render loop
  useFrame((state) => {
    Object.values(actions).map((animation: any) => {
      animation.time = lerp(animation.time, animation.getClip().duration * props.scroll.current, 0.025)
    });
  });

  //helpers
  const { viewport } = useThree()

  return (
    <group ref={group} rotation={[0, -1.5, 0]} scale={size(1.5, viewport.width / 10, 1.75)} position={[size(0.01, viewport.width / 5, 20), viewport.width / 20 - size(6, viewport.width / 10, 10.75), 0]} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[-6.21, 1.343, -0.845]} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} position={[-0.032, 5.542, 3.904]} >{brain}</mesh>
        <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials.rock} scale={2.444} />
        <group name="Circle002" scale={2.444}>
          <mesh name="Circle002_1" geometry={nodes.Circle002_1.geometry} material={materials.snow} />
          <mesh name="Circle002_2" geometry={nodes.Circle002_2.geometry} material={materials.rock} />
        </group>
        <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} position={[-0.011, 4.12, 1.495]} rotation={[-Math.PI, 0.215, -Math.PI]} scale={[-0.012, -1.257, -0.012]} >{rope}</mesh>
        <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials.rock} scale={2.444} />
        <mesh name="Circle001_cell" geometry={nodes.Circle001_cell.geometry} material={materials.rock} position={[0.841, 0.949, -0.957]} />
        <group name="Circle001_cell002" position={[-0.935, 0.828, -1.125]}>
          <mesh name="Circle001_cell001" geometry={nodes.Circle001_cell001.geometry} material={materials.rock} />
          <mesh name="Circle001_cell001_1" geometry={nodes.Circle001_cell001_1.geometry} material={materials.rock} />
        </group>
        <group name="Circle001_cell004" position={[-1.924, 0.669, 0.75]}>
          <mesh name="Circle001_cell002_1" geometry={nodes.Circle001_cell002_1.geometry} material={materials.rock} />
          <mesh name="Circle001_cell002_2" geometry={nodes.Circle001_cell002_2.geometry} material={materials.rock} />
        </group>
        <group name="Circle001_cell005" position={[0.64, 1.196, -0.168]}>
          <mesh name="Circle001_cell003" geometry={nodes.Circle001_cell003.geometry} material={materials.rock} />
          <mesh name="Circle001_cell003_1" geometry={nodes.Circle001_cell003_1.geometry} material={materials.rock} />
        </group>
        <group name="Circle001_cell006" position={[0.041, 0.785, -1.623]}>
          <mesh name="Circle001_cell004_1" geometry={nodes.Circle001_cell004_1.geometry} material={materials.rock} />
          <mesh name="Circle001_cell004_2" geometry={nodes.Circle001_cell004_2.geometry} material={materials.rock} />
        </group>
        <group name="Circle001_cell007" position={[2.081, 0.734, 0.702]}>
          <mesh name="Circle001_cell005_1" geometry={nodes.Circle001_cell005_1.geometry} material={materials.rock} />
          <mesh name="Circle001_cell005_2" geometry={nodes.Circle001_cell005_2.geometry} material={materials.rock} />
        </group>
        <group name="Circle001_cell009" position={[0.258, 0.736, -0.092]}>
          <mesh name="Circle001_cell006_1" geometry={nodes.Circle001_cell006_1.geometry} material={materials.rock} />
          <mesh name="Circle001_cell006_2" geometry={nodes.Circle001_cell006_2.geometry} material={materials.rock} />
        </group>
        <group name="Circle001_cell010" position={[0.928, 0.74, 0.099]}>
          <mesh name="Circle001_cell007_1" geometry={nodes.Circle001_cell007_1.geometry} material={materials.rock} />
          <mesh name="Circle001_cell007_2" geometry={nodes.Circle001_cell007_2.geometry} material={materials.rock} />
        </group>
        <group name="Circle001_cell011" position={[1.333, 1.196, -0.092]}>
          <mesh name="Circle001_cell008" geometry={nodes.Circle001_cell008.geometry} material={materials.rock} />
          <mesh name="Circle001_cell008_1" geometry={nodes.Circle001_cell008_1.geometry} material={materials.rock} />
        </group>
        <group name="Circle001_cell013" position={[0.25, 1.084, -1.269]}>
          <mesh name="Circle001_cell009_1" geometry={nodes.Circle001_cell009_1.geometry} material={materials.rock} />
          <mesh name="Circle001_cell009_2" geometry={nodes.Circle001_cell009_2.geometry} material={materials.rock} />
        </group>
        <group name="Circle001_cell014" position={[-1.246, 1.007, 0.265]}>
          <mesh name="Circle001_cell010_1" geometry={nodes.Circle001_cell010_1.geometry} material={materials.rock} />
          <mesh name="Circle001_cell010_2" geometry={nodes.Circle001_cell010_2.geometry} material={materials.rock} />
        </group>
        <group name="Circle001_cell015" position={[1.527, 0.988, 0.406]}>
          <mesh name="Circle001_cell011_1" geometry={nodes.Circle001_cell011_1.geometry} material={materials.rock} />
          <mesh name="Circle001_cell011_2" geometry={nodes.Circle001_cell011_2.geometry} material={materials.rock} />
        </group>
        <group name="Circle001_cell016" position={[-0.917, 0.993, -0.494]}>
          <mesh name="Circle001_cell012" geometry={nodes.Circle001_cell012.geometry} material={materials.rock} />
          <mesh name="Circle001_cell012_1" geometry={nodes.Circle001_cell012_1.geometry} material={materials.rock} />
        </group>
        <group name="Circle001_cell017" position={[0.094, 0.933, 1.009]}>
          <mesh name="Circle001_cell013_1" geometry={nodes.Circle001_cell013_1.geometry} material={materials.rock} />
          <mesh name="Circle001_cell013_2" geometry={nodes.Circle001_cell013_2.geometry} material={materials.rock} />
        </group>
        <group name="Circle001_cell019" position={[-0.395, 1.05, 0.392]}>
          <mesh name="Circle001_cell014_1" geometry={nodes.Circle001_cell014_1.geometry} material={materials.rock} />
          <mesh name="Circle001_cell014_2" geometry={nodes.Circle001_cell014_2.geometry} material={materials.rock} />
        </group>
        <group name="Circle001_cell021" position={[-0.533, 1.224, -0.827]}>
          <mesh name="Circle001_cell015_1" geometry={nodes.Circle001_cell015_1.geometry} material={materials.rock} />
          <mesh name="Circle001_cell015_2" geometry={nodes.Circle001_cell015_2.geometry} material={materials.rock} />
        </group>
        <group name="Circle001_cell022" position={[-0.235, 0.83, -1.009]}>
          <mesh name="Circle001_cell016_1" geometry={nodes.Circle001_cell016_1.geometry} material={materials.rock} />
          <mesh name="Circle001_cell016_2" geometry={nodes.Circle001_cell016_2.geometry} material={materials.rock} />
        </group>
        <group name="Circle001_cell023" position={[1.221, 0.864, -0.302]}>
          <mesh name="Circle001_cell017_1" geometry={nodes.Circle001_cell017_1.geometry} material={materials.rock} />
          <mesh name="Circle001_cell017_2" geometry={nodes.Circle001_cell017_2.geometry} material={materials.rock} />
        </group>
        <group name="Circle001_cell025" position={[0.819, 1.07, 0.738]}>
          <mesh name="Circle001_cell018" geometry={nodes.Circle001_cell018.geometry} material={materials.rock} />
          <mesh name="Circle001_cell018_1" geometry={nodes.Circle001_cell018_1.geometry} material={materials.rock} />
        </group>
        <group name="Circle001_cell026" position={[-1.219, 0.88, 1.017]}>
          <mesh name="Circle001_cell019_1" geometry={nodes.Circle001_cell019_1.geometry} material={materials.rock} />
          <mesh name="Circle001_cell019_2" geometry={nodes.Circle001_cell019_2.geometry} material={materials.rock} />
        </group>
        <group name="Circle001_cell027" position={[-0.836, 1.071, -1.19]}>
          <mesh name="Circle001_cell020" geometry={nodes.Circle001_cell020.geometry} material={materials.rock} />
          <mesh name="Circle001_cell020_1" geometry={nodes.Circle001_cell020_1.geometry} material={materials.rock} />
        </group>
        <group name="Circle001_cell028" position={[1.749, 0.955, 0.091]}>
          <mesh name="Circle001_cell021_1" geometry={nodes.Circle001_cell021_1.geometry} material={materials.rock} />
          <mesh name="Circle001_cell021_2" geometry={nodes.Circle001_cell021_2.geometry} material={materials.rock} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/mountain.glb')
