/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/neurons2.glb --types --output src/Neurons2.tsx 
*/

import * as THREE from 'three'
import React, { MutableRefObject, useEffect, useLayoutEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations, Float } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame, useThree } from '@react-three/fiber'
import { useAnimation } from 'framer-motion'
import { useAtom } from 'jotai'
import { useSearchParams } from 'next/navigation'
import { useRouter } from 'next/router'
import { lerp } from 'three/src/math/MathUtils.js'
import { loc } from './ts/atoms'
import { motion as motion3d } from "framer-motion-3d"

type GLTFResult = GLTF & {
  nodes: {
    Icosphere: THREE.Mesh
    Icosphere002: THREE.Mesh
    Icosphere003: THREE.Mesh
    Icosphere001: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

type ActionName = 'Icosphere' | 'Key.002Action.003' | 'Icosphere.002' | 'Key.003Action.003' | 'Icosphere.003' | 'KeyAction.003' | 'Icosphere.001' | 'Key.001Action.003'
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}
type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

type NeuronsProps = {
  scroll: MutableRefObject<number>;
  props?: JSX.IntrinsicElements['group']
}

const materialVariants = {
  initial: { opacity: 0 },
  enter: {
    opacity: 1,
    transition: {
      type: "spring",
      damping: 10,
      stiffness: 50,
      restDelta: 0.1,
    }
  },
  exit: {
    opacity: 0, roughness: 1, transition: {
      type: "spring",
      damping: 10,
      stiffness: 50,
      restDelta: 0.1, delay: 0.25
    }
  },
};

export function Neurons(props: NeuronsProps) {
  const group: any = useRef<THREE.Group>()
  const { nodes, materials, animations, userData, scene }: any = useGLTF('/neurons2.glb') as GLTFResult
  const { actions }: any = useAnimations(animations, group)
  //atoms
  const [location, setLocation] = useAtom(loc)
  // controls
  const neuronMaterialControls = useAnimation();
  useEffect(() => {
    Object.values(actions).map((animation: any) => {
      animation.reset().fadeIn(0.5).play().paused = true
    })
    console.log(nodes, userData, scene)
  }, [])
  // router
  const router = useRouter()
  // search params
  const searchParams = useSearchParams();
  // mount states
  const [isInPage, setIsInPage] = useState(false);
  const [disposed, setDisposed] = useState(false);
  //helpers
  const { viewport } = useThree();

  //render loop
  useFrame((state) => {
    Object.values(actions).map((animation: any) => {
      animation.time = lerp(animation.time, animation.getClip().duration * props.scroll.current * 5, 0.02)
    });
  });

  //uef
  useEffect(() => {
    if (
      location === "science" && router.pathname === "/" && searchParams.get("test") === null || false) {
      setDisposed(false), setIsInPage(true);
    } else {
      neuronMaterialControls.start("exit").then(() => {
        setTimeout(() => {
          setDisposed(true),
            setIsInPage(false);
        }, 500)
      })
    }
  }, [router.pathname, searchParams, location])

  useEffect(() => {
    isInPage && neuronMaterialControls.start("enter")
  }, [isInPage]);

  const ref1: any = useRef();
  const ref2: any = useRef();
  const ref3: any = useRef();
  const ref4: any = useRef();


  useLayoutEffect(() => {
    ref1.current?.updateMorphTargets();
    ref2.current?.updateMorphTargets();
    ref3.current?.updateMorphTargets();
    ref4.current?.updateMorphTargets();

  }, []);


  // materials
  const neuron = <motion3d.meshStandardMaterial
    transparent
    color={"#ebf0d9"}
    initial="initial"
    animate={neuronMaterialControls}
    exit="exit"
    variants={materialVariants}
  />

  return (
    <Float visible={!disposed} rotationIntensity={0.1} floatIntensity={0.2} floatingRange={[-0.2, 0.2]}>
      <group visible={!disposed} ref={group} rotation={[Math.PI / 1, 0, 0]} scale={2} position={[0, 0, 0]} {...props} dispose={null}>
        <group name="Scene">
          <mesh ref={ref1} name="Icosphere" geometry={nodes.Icosphere.geometry}  >{neuron}</mesh>
          <mesh ref={ref2} name="Icosphere002" geometry={nodes.Icosphere002.geometry} position={[1.075, 11.414, -2.974]} rotation={[-0.664, 0.367, 2.791]} >{neuron}</mesh>
          <mesh ref={ref3} name="Icosphere003" geometry={nodes.Icosphere003.geometry} position={[-0.825, 3.578, 2.974]} rotation={[-0.227, 0.251, 0.549]} >{neuron}</mesh>
          <mesh ref={ref4} name="Icosphere001" geometry={nodes.Icosphere001.geometry} position={[1.871, 7.938, 1.395]} rotation={[-0.237, 0.09, 1.262]} scale={0.876}>{neuron}</mesh>
        </group>
      </group>
    </Float>
  )
}

useGLTF.preload('/neurons2.glb')
