/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/newHead.glb --types --output src/NewHead.tsx 
*/

import * as THREE from 'three'
import React, { useEffect, useRef, useState } from 'react'
import { MeshTransmissionMaterial, useAspect, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { motion as motion3d } from "framer-motion-3d"
import { useThree } from '@react-three/fiber'
import { useAtom } from 'jotai'
import { productViewer, globalTarget, orbitTarget, loc } from './ts/atoms'
import { size as s } from './ts/utils';

type GLTFResult = GLTF & {
  nodes: {
    Shape_IndexedFaceSet001: THREE.SkinnedMesh
    base: THREE.Mesh
    right_hemisphere: THREE.Mesh
    left_hemisphere: THREE.Mesh
    head: THREE.Mesh
    cerebellum: THREE.Mesh
    stem: THREE.Mesh
    Bone001: THREE.Bone
    Bone002: THREE.Bone
    Bone004: THREE.Bone
    Bone008: THREE.Bone
    Bone014: THREE.Bone
    Bone018: THREE.Bone
  }
  materials: {}
  animations: any[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['skinnedMesh'] | JSX.IntrinsicElements['mesh'] | JSX.IntrinsicElements['bone']>>

export function NewHead(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/newHead.glb') as GLTFResult
  const [pvAtom, setPVAtom] = useAtom(productViewer);
  const [gTarget, setGTarget] = useAtom(globalTarget);
  const [target, setTarget] = useAtom(orbitTarget);
  const [app, setApp] = useAtom(loc);
  const [pos, setPos] = useState<any>([]);
  const [scl, setScale] = useState<any>([]);
  const { viewport, size } = useThree();
  const [w, h] = useAspect(size.width, size.height);

  //refs
  const group: any = useRef(!null);



  useEffect(() => {
    const scale: any = [
      (pvAtom?.width / window.innerWidth) * viewport?.width,
      (pvAtom?.height / window.innerHeight) * viewport?.height,
      1,
    ];
    const position: any = [
      ((pvAtom?.width / window.innerWidth) * viewport.width) / 2 -
      viewport.width / 2 +
      (pvAtom?.left / window.innerWidth) * viewport.width,
      -s(3, viewport.width / 5, 7) -
      ((pvAtom?.height / window.innerHeight) * viewport.height) / 2 +
      viewport.height / 2 -
      (pvAtom?.top / window.innerHeight) * viewport.height,
      0,
    ];
    setPos(position);
    setScale(scale);
  }, [pvAtom]);
  const hand2Material = (
    <motion3d.meshStandardMaterial
      color="#cfab7c"
      transparent
      toneMapped
    />
  );

  const bmRef = useRef<any>(!null);
  const brain_material = (
    <motion3d.meshStandardMaterial
      ref={bmRef}
      exit="exit"
      color="#87e727"
      opacity={1}
      transparent
      toneMapped
    />
  );

  const glassMat: any = useRef();
  const glass = (
    <MeshTransmissionMaterial
      ref={glassMat}
      samples={8}
      reflectivity={0.85}
      sheenRoughness={0}
      iridescence={0.5}
      iridescenceIOR={0.95}
      resolution={1024 * 2}
      thickness={0}
      anisotropy={0.75}
      anisotropicBlur={0.75}
      clearcoat={1}
      clearcoatRoughness={0}
      transparent
      color="#b7eba7"
      roughness={0}
      chromaticAberration={0.65}
    />
  );
  return (
    <group {...props} position={pos} dispose={null} scale={s(3, viewport.width / 5, 7)} rotation={[0, -Math.PI / 1.15, 0]}>
      <group position={[0.294, 0.649, -0.045]} rotation={[-Math.PI / 2, 0.565, Math.PI / 2]} scale={0.258}>
        <primitive object={nodes.Bone001} />
        <primitive object={nodes.Bone002} />
        <primitive object={nodes.Bone004} />
        <primitive object={nodes.Bone008} />
        <primitive object={nodes.Bone014} />
        <primitive object={nodes.Bone018} />
        <skinnedMesh geometry={nodes.Shape_IndexedFaceSet001.geometry} skeleton={nodes.Shape_IndexedFaceSet001.skeleton} >{hand2Material}</skinnedMesh>
      </group>
      <mesh geometry={nodes.base.geometry} position={[0.137, 1.743, 0]} rotation={[Math.PI, 0, Math.PI]} scale={[0.337, 0.325, 0.308]} >{brain_material}</mesh>
      <mesh geometry={nodes.right_hemisphere.geometry} position={[0.137, 1.743, 0]} rotation={[Math.PI, 0, Math.PI]} scale={[0.337, 0.325, 0.308]} >{brain_material}</mesh>
      <mesh geometry={nodes.left_hemisphere.geometry} position={[0.137, 1.743, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.337, -0.325, -0.308]} >{brain_material}</mesh>
      <mesh geometry={nodes.head.geometry} position={[0.184, 1.584, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[4.297, 4.297, 4.243]} >{glass}</mesh>
      <mesh geometry={nodes.cerebellum.geometry} position={[-0.066, 1.557, 0]} scale={[0.123, 0.075, 0.123]} >{brain_material}</mesh>
      <mesh geometry={nodes.stem.geometry} position={[0.071, 1.561, 0]} scale={[0.083, 0.206, 0.083]} >{brain_material}</mesh>
    </group>
  )
}

useGLTF.preload('/newHead.glb')
