/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/public.glb --types --output src/Public.tsx 
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.SkinnedMesh
    mixamorigHips: THREE.Bone
  }
  materials: {}
  animations: GLTFAction[]
}

type ActionName = 'Armature|mixamo.com|Layer0'
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}
type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['skinnedMesh'] | JSX.IntrinsicElements['bone']>>

export function Public(props: JSX.IntrinsicElements['group']) {
  const group: any = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/public.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  const mat = <meshStandardMaterial color="white" toneMapped />
  useEffect(() => {
    actions['Armature|mixamo.com|Layer0']?.play()
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Cube" geometry={nodes.Cube.geometry} skeleton={nodes.Cube.skeleton}>{mat}</skinnedMesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/public.glb')
